language: ruby
cache: bundler

rvm:
  - jruby-head
  - 2.1.2

script: 'bundle exec rspec spec'

notifications:
  email:
    recipients:
      - eric@dobbse.net
    on_failure: change
    on_success: never